"""Validation shared by report delivery channels."""

import hashlib
import json
import os
from datetime import datetime, timedelta, timezone
from pathlib import Path


def load_current_report(report_path: Path, manifest_path: Path):
    """Reject old, incomplete, modified or unrelated reports before delivery."""
    report_bytes = report_path.read_bytes()
    report = report_bytes.decode('utf-8')
    manifest = json.loads(manifest_path.read_text(encoding='utf-8'))
    now = datetime.now(timezone.utc)
    generated = datetime.fromisoformat(manifest['generated_at'])
    if generated.tzinfo is None or not now - timedelta(hours=12) <= generated <= now + timedelta(minutes=5):
        raise ValueError('Report is stale or has an invalid generation timestamp')
    for env_name, key in (('GITHUB_RUN_ID', 'github_run_id'), ('GITHUB_RUN_ATTEMPT', 'github_run_attempt')):
        expected = os.getenv(env_name)
        if expected and str(manifest.get(key)) != expected:
            raise ValueError('Report was not generated by this workflow run/attempt')
    if hashlib.sha256(report_bytes).hexdigest() != manifest.get('report_sha256'):
        raise ValueError('Report checksum does not match this scan manifest')
    if manifest.get('analyzed', 0) <= 0 or 'END OF SCAN' not in report:
        raise ValueError('Report has no analyzed stocks or is incomplete')
    return report, manifest
